# Runtime
SLEEP_SECONDS = 30

# Portfolio
STARTING_CASH = 100

# Market filters
MIN_VOLUME_24H = 1000
MIN_LIQUIDITY = 500
MAX_SPREAD = 0.03
MIN_PRICE = 0.20
MAX_PRICE = 0.90
MIN_YES_ASK_DOLLARS = 25
MAX_DAILY_LOSS = 0.25
COOLDOWN_AFTER_FILL_SECONDS = 120

# Imbalance
IMBALANCE_BUY_THRESHOLD = 1.5
IMBALANCE_SELL_THRESHOLD = 0.55
IMBALANCE_HISTORY_LENGTH = 3
MIN_IMBALANCE_CONFIRMATIONS = 2

# Market making
MIN_MM_SPREAD = 0.02
QUOTE_OFFSET = 0.005

# Live minimum order size on Polymarket is effectively 5 shares.
# Keep this at 5 while live-testing with small capital.
ORDER_SIZE = 5

MAX_POSITION_SIZE = 50
MAX_POSITION_AGE_MINUTES = 30
MIN_ORDER_AGE_SECONDS = 30
PARTIAL_FILL_FRACTION = 0.5
MIN_PARTIAL_FILL_SIZE = 1

LOW_VOLUME_FILL_PROBABILITY = 0.15
MEDIUM_VOLUME_FILL_PROBABILITY = 0.35
HIGH_VOLUME_FILL_PROBABILITY = 0.55

QUOTE_MAX_AGE_SECONDS = 600
MAX_ASK_TO_BID_SIZE_RATIO_FOR_BUY = 0.75
COOLDOWN_AFTER_CANCEL_SECONDS = 300

MEDIUM_VOLUME_24H = 50_000
HIGH_VOLUME_24H = 250_000

SMALL_ORDER_SIZE = 5
LARGE_ORDER_SIZE = 25
LARGE_ORDER_FILL_PENALTY = 0.5

MAX_DEPTH_FILL_FRACTION = 0.25
QUEUE_DEPTH_LOW = 25
QUEUE_DEPTH_HIGH = 250
QUEUE_PENALTY_MIN_MULTIPLIER = 0.4

AGGRESSIVE_EXIT_SLIPPAGE = 0.001
MAX_BUYS_PER_MARKET = 1

MEAN_REVERSION_HISTORY_LENGTH = 5
MAX_BUY_EXTENSION_ABOVE_MEAN = 0.015
COOLDOWN_AFTER_EXIT_SECONDS = 300
MIN_PRICE_STABILITY = 0.002
POSITION_EPSILON = 1e-8

# Risk
# These are now sized for a small live test wallet.
MAX_POSITION_VALUE_PER_MARKET = 5
MAX_TOTAL_POSITION_VALUE = 7
MAX_OPEN_ORDER_VALUE = 7
MAX_MARKET_LOSS_PCT = 0.10
MAX_CATEGORY_EXPOSURE = 2

# Logs
TRADE_LOG_FILE = "logs/paper_fills.csv"
EQUITY_LOG_FILE = "logs/equity_curve.csv"

# Live fill validation
LIVE_FILL_VALIDATION_LOG_FILE = "logs/live_fill_validation.csv"
LIVE_ENTRY_DIAGNOSTICS_LOG_FILE = "logs/live_entry_diagnostics.csv"

# Blacklist
MARKET_BLACKLIST_KEYWORDS = []
MARKET_BLACKLIST_CONDITION_IDS = []

# Whitelist
USE_MARKET_WHITELIST = False
MARKET_WHITELIST_KEYWORDS = []
MARKET_WHITELIST_CONDITION_IDS = []

# Execution mode
MODE = "live"  # paper or live

# Live trading safety
LIVE_TRADING_ENABLED = True

# Live order controls
LIVE_ORDER_SIZE = 5
MAX_LIVE_ORDER_SIZE = 5
MAX_LIVE_ORDER_VALUE = 5.00
MAX_LIVE_POSITION_VALUE = 5.00
MAX_LIVE_TOTAL_EXPOSURE = 7.00

LIVE_ORDER_TYPE = "GTC"
LIVE_TICK_SIZE = "0.01"
LIVE_NEG_RISK = False

# Live startup safety
LIVE_ADOPT_OPEN_ORDERS = True
LIVE_REFUSE_START_WITH_OPEN_ORDERS = True

# Live state persistence
LIVE_STATE_FILE = "logs/live_state.json"

# Live trade reconstruction
# Keep False because this account has old/manual trades.
LIVE_RECONSTRUCT_POSITIONS_FROM_TRADES = False
LIVE_MAX_RECONSTRUCT_TRADES = 500

# Tiny live test safety
LIVE_TEST_MAX_ORDER_VALUE = 1.00
LIVE_TEST_DEFAULT_SIZE = 5
LIVE_TEST_DEFAULT_PRICE = 0.01

# Live logs
LIVE_TRADE_LOG_FILE = "logs/live_fills.csv"
LIVE_EQUITY_LOG_FILE = "logs/live_equity_curve.csv"
LIVE_ORDER_LOG_FILE = "logs/live_orders.csv"

# Live exposure safety
LIVE_MIN_USDC_BALANCE = 1
LIVE_REQUIRE_ALLOWANCE = True
ALLOW_NEW_ENTRIES = True
ALLOW_POSITION_EXITS = True

# Live startup conflict policy
LIVE_MAX_POSITION_RECONCILIATION_DIFF = 0.000001

# Live API retry
LIVE_API_MAX_RETRIES = 3
LIVE_API_RETRY_SLEEP_SECONDS = 2

# Live credentials
POLYMARKET_HOST = "https://clob.polymarket.com"
POLYMARKET_CHAIN_ID = 137
POLYMARKET_PRIVATE_KEY_ENV = "POLYMARKET_PRIVATE_KEY"
POLYMARKET_FUNDER_ENV = "POLYMARKET_FUNDER"
POLYMARKET_SIGNATURE_TYPE = 1

# Bad market cooldown
BAD_MARKET_COOLDOWN_SECONDS = 6 * 60 * 60
BAD_MARKET_STALE_EXIT_LIMIT = 1
BAD_MARKET_DRAWDOWN_EXIT_LIMIT = 1

# Live kill switch
LIVE_KILL_SWITCH_FILE = "logs/LIVE_KILL_SWITCH"

# Manual news danger switch
NEWS_DANGER_MODE = False

NEWS_DANGER_KEYWORDS = [
    "iran",
    "hormuz",
    "airspace",
    "blockade",
    "peace deal",
    "diplomatic meeting",
]